package com.groupaugmentation;


import com.groupaugmentation.util.RandomNumberGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;

public class Individual {

    private final Logger log = LoggerFactory.getLogger(Individual.class);

    private BigDecimal alpha;

    private BigDecimal beta;

    private BigDecimal drift;


    /**
     * This constructor is only used when the Individual is generated by a mother
     * is called when a new offspring is generated
     *
     * @param mother the mother of the individual
     */
    public Individual(Individual mother) {
        if (mother.getFishType() != FishType.BREEDER) {
            log.error("Something went wrong you cannot create an Individual from a non Breeder");
        }

        //modify alpha beta and drift for the new generation
        RandomNumberGenerator rng = RandomNumberGenerator.getInstance();

        this.alpha = mother.getAlpha();
        this.beta = mother.getBeta();
        this.drift = mother.getDrift();
        this.fishType = FishType.HELPER;

        if (rng.getNextRealUniform() < Settings.MUTATION_ALPHA) {
            this.alpha = this.alpha.add(rng.getNextGaussianAlpha());
        }

        if (rng.getNextRealUniform() < Settings.MUTATION_BETA) {
            this.beta = this.beta.add(rng.getNextGaussianBeta());
        }

        if (rng.getNextRealUniform() < Settings.MUTATION_DRIFT) {
            this.drift = this.drift.add(rng.getNextGaussianDrift());
        }

        log.trace("New Offspring with ALPHA: " + this.alpha + " BETA: " + this.beta + " DRIFT: " + this.drift);

    }


    public Individual(BigDecimal alpha, BigDecimal beta, FishType fishType) {
        this(alpha, beta);
        this.fishType = fishType;
    }


    public Individual(BigDecimal alpha, BigDecimal beta) {
        this.fishType = FishType.HELPER;
        this.alpha = alpha;
        this.beta = beta;
        this.drift = RandomNumberGenerator.getInstance().getNextInitDriftNormal();
    }

    private FishType fishType;


    public FishType getFishType() {
        return fishType;
    }

    public void setFishType(FishType fishType) {
        this.fishType = fishType;
    }

    public BigDecimal getAlpha() {
        return alpha;
    }

    public BigDecimal getBeta() {
        return beta;
    }

    public BigDecimal getDrift() {
        return drift;
    }
}
